[build-system]
requires = ["setuptools", "wheel", "cython", "numpy >= 1.21"]
build-backend = "setuptools.build_meta"

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"

[[tool.mypy.overrides]]
module = "sklearn.preprocessing.*"
ignore_missing_imports = true
